version: '3.8'

services:
  # BHABITS CB INSIGHT - Full Stack Crypto Dashboard
  bhabits-cb-insight:
    build: .
    container_name: bhabits-cb-insight
    ports:
      - "3000:3000"  # Frontend
      - "5001:5001"  # Backend API
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount for development (uncomment for dev mode)
      # - ./backend:/app/backend
      # - ./frontend/src:/app/frontend/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/crypto"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - bhabits-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: bhabits-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates here if needed
      # - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - bhabits-cb-insight
    restart: unless-stopped
    networks:
      - bhabits-network
    profiles:
      - production

networks:
  bhabits-network:
    driver: bridge

# Optional: Add persistent volumes for logs or data
volumes:
  app-logs:
    driver: local
